version: "3.9"
services:
  dotnet-service:
    image: dotnet-service
    ports:
      - 80:80
    depends_on:
      - mysql-piss
      - flask-service

  flask-service:
    image: flask-service
    ports:
      - 5002:5002

  mysql-piss:
    image: mysql-piss
    ports:
      - 3306:3306
